language: csharp
os: linux # Ubuntu 14.04
dist: trusty
sudo: required
dotnet: 1.0.0-preview2-003121
services:
  - docker
env:
  DOCKER_COMPOSE_VERSION: 1.4.2

script:
  - docker-compose build
  - docker-compose up -d
  - docker-compose stop
