language: csharp
os: linux # Ubuntu 14.04
dist: trusty
sudo: required
dotnet: 1.0.0-preview2-003121
services:
  - docker
env:
  DOCKER_COMPOSE_VERSION: 1.4.2

script:
  # Run unit tests
  - dotnet restore
  - cd ./Crunch.Tests
  - dotnet build
  - dotnet test
  # Launch application
  - cd ../Crunch
  - docker-compose build
  - docker-compose up -d
  - docker-compose stop
  # Once this is running, we should have some integration tests
