language: csharp
os: linux
dist: trusty
sudo: required
dotnet: 1.0.0-preview2-003121
services:
- docker
env:
  DOCKER_COMPOSE_VERSION: 1.4.2
before_install:
- dotnet restore
script:
- cd ./Crunch.Tests
- dotnet build
- dotnet test
- cd ../
- docker-compose -f docker-compose.yml -f docker-compose.test.yml run test ./wait-for-it.sh
  web:5000 -- dotnet test
after_success:
# AWS
# - ./deploy/aws/docker_push.sh
# - ./deploy/aws/push_to_ecs.sh
# Heroku
 - ./deploy/heroku/docker_push.sh
