language: csharp
os: linux # Ubuntu 14.04
dist: trusty
sudo: required
dotnet: 1.0.0-preview2-003121
services:
  - docker
env:
  DOCKER_COMPOSE_VERSION: 1.4.2

before_install:
  # Run unit tests
  - dotnet restore
script:
  - cd ./Crunch.Tests
  - dotnet build
  - dotnet test
  # Launch application and tests
  - cd ../
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml run test ./wait-for-it.sh web:5000 -- dotnet test

after_success:
  # When we need to push up the docker container
  - docker-compose -f docker-compose.yml -p crunch build
  - docker images
  - ./docker_push.sh
