language: csharp
os: linux # Ubuntu 14.04
dist: trusty
sudo: required
dotnet: 1.0.0-preview2-003121
services:
  - docker
env:
  DOCKER_COMPOSE_VERSION: 1.4.2

before_install:
  - curl -L https://github.com/docker/machine/releases/download/v0.8.0/docker-machine-`uname -s`-`uname -m` >/usr/local/bin/docker-machine && \
  - chmod +x /usr/local/bin/docker-machine
  # Run unit tests
  - dotnet restore
  - cd ./Crunch.Tests
  - dotnet build
  - dotnet test
  # Launch application
  - cd ../Crunch
  - docker-compose build
  - docker-compose up -d
  # Once this is running, we should have some integration tests
  - export DOCKER_TEST_ADDRESS="$(docker-machine ip default)"
  - echo $DOCKER_TEST_ADDRESS
  - echo $DOCKER_HOST_ADDRESS
  - cd ../Crunch.Integration.Tests
  - dotnet test
  # Clean up the running instance
  - cd ../Crunch
  - docker-compose stop

  # When we need to push up the docker container
  # after_success:
  # - if [ "$TRAVIS_BRANCH" == "master" ]; then
  #   docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  #   docker push USER/REPO;
  #   fi
  