redis:
  image: redis:latest
  command: redis-server --appendonly yes
  volumes:
    - ./Crunch/redis-data:/data
web:
  environment:
    - PORT=5000
  build: ./Crunch
  command: dotnet watch run
  ports:
    - "5000:5000"
  volumes:
    - ./Crunch:/app
  links:
    - redis