redis:
  image: redis:latest
  command: redis-server --appendonly yes
  volumes:
    - ./data:/data
web:
  environment:
    - PORT=5000
  build: .
  ports:
    - "5000:5000"
  volumes:
    - .:/app
  links:
    - redis